UMS: Fix comparison of unsigned variable against < 0.
Pointed out by clang:

../../src/radeon_crtc.c:242:18: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
                        error = error < 0 ? 0xffffffff : error;
                                ~~~~~ ^ ~

If a UMS regression is bisected to this commit, the assignment should probably
just be removed, as it's a no-op in the current form.