Remove unused local variable 'path'.
../../src/radeon_probe.c: In function 'radeon_platform_probe':
../../src/radeon_probe.c:270:11: error: unused variable 'path' [-Werror=unused-variable]

Reviewed-by: Alex Deucher <aleander.deucher@amd.com>
Signed-off-by: Michel Dänzer <michel.daenzer@amd.com>